# EDS 220: Lesson 1

## Numpy

- one of the core packages for numerical computing in Python
- many packages built on top of numpy
- numpy bas been optimized for processing (will be faster due to memory access)


In [2]:
# import Numpy for standard abbreviation
import numpy as np

## Variables
a name we assign a particular object in Python

In [3]:
# assign a small array to a variable, a
a = np.array( [ [1,1,2],[3,5,8] ] )

When we run the cell, we store the variable and its value. We can see the variable's value in 2 ways:

In [4]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [6]:
print(a) #typically displays it nicer

[[1 1 2]
 [3 5 8]]


### Naming variables
In this class we will use 'snake_case' for naming variables

### Variables and objects
**object**: a bundle of properties and actions about something specific

Example:
- object: dataframe
- properties: number of rows, names of columns, data
- actions: selecting a row, adding a column

A variable is a name we give a specific object, and the same object can be referenced by different variables.

Example:
- the Sun (actual star at the senter of the solar system) = object
- sol = Spanish word for Sun = variable
- soleil = French for Sun = another variable

In practice, we will use objects and variables interchangeably

## Types

Each object has a type

type = what kind of object it is

We can also call the type of the object the **class** of the object

We can see the type/class of an object by using the type function

In [9]:
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The numpy.ndarray is the core object/datatype in the NumPy package. We can check the type of an entry in the array by indexing. 

In [13]:
# access the first row and first column
# remember, indexing starts at 0!

print(a [0,0] )
type(a [0,0] )

1


numpy.int64

In [15]:
# how would you access the value 5 in array a?

print(a [1,1] )

5


## Functions

print was our first example of a python function! :) 

A function:
- take in a set of **arguments** separated by commas, and
- use those arguments to produce some **output**

arguement = paramater : you might see argument more often in dicumentation

We can ask information about a function using ? before the function

In [20]:
# get info about print
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

- first line: function showing all of its arguments in parenthesis
- then a short description of what the function does
- finally, a list of the arguments and brief explanation of each of them

Different types of arguments inside the parenthesis. Roughly speaking, there are 2 types of arguments:

- **non-optional arguments**: arguments you need to specify for the function to do something
- **optional arguments**: arguments prefilled with a defauly value but we can override them. Optional args appear inside the parenthesis () in the form below when you look up the documentation

optional argument = default_value

In [23]:
# let's change the defauly argument for the end of the print function
print("change it to a smiley", end= ':)' )

change it to a smiley:)